name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PUBLIC_MATOMO_URL: https://rp1.amase.cc/matomo/
  PUBLIC_MATOMO_SITE_ID: 1

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Restore cached images
        id: cache-images-restore
        uses: actions/cache/restore@v4
        with:
          path: cache
          key: Images-${{ runner.os }}
      - name: Install, build, and upload your site
        uses: withastro/action@v3
      - name: Install gh actions-cache extension
        run: gh extension install actions/gh-actions-cache
        env:
         GH_TOKEN: ${{ github.token }}
      - name: Check if images cache exists for current branch
        id: actions-cache-list
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo "RESULT=$(gh actions-cache list --branch ${{ github.ref }} --key Images-)" >> $GITHUB_OUTPUT
      - name: Clear existing images cache
        if: ${{ steps.actions-cache-list.outputs.RESULT != '' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh actions-cache delete ${{ steps.cache-images-restore.outputs.cache-primary-key }} --branch ${{ github.ref }} --confirm
      - name: Cache images
        uses: actions/cache/save@v4
        with:
          path: cache
          key: ${{ steps.cache-images-restore.outputs.cache-primary-key }}
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4